# -*- coding: utf-8 -*-
"""zuhra.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1znyavtIRHjm9cANeNebESZqIamXmIADM
"""

"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQ2rOOmqpxrWf4Xfga4-dinPPDSz0OQo
"""

import pandas as pd
oqtuvchilar=pd.DataFrame({
                    "FISH":['Xalilov.D.A', 'Abdullayeva.M.A', 'Qadamova.Z.E', 'Jo`rayeva.G.F', 'Xonto`rayev.S.I', 'Qurbonova.G.M', 'Djalilov.M.L', 'Rahmatov.R.R', 'Tillaboyev.M.G', 'Turdimatov.M.M'],
                    "Fan turi":['Suniy intelekt asoslari','Malumotlar tuzilmasi va algoritm','Suniy intelekt asoslari','Elektronika va sxemalar','Malumotlar tuzilmasi va algoritm','Kompyuterni tashkil etish', 'Kompyuterni tashkil etish','Kiberxavfsizlik asoslari', 'Elektronika va sxemalar','Kiberxavfsizlik asoslari'],

                    "Dars mashg`uloti":['Maruza','Amaliy','Amaliy','Maruza','Maruza','Amaliy','Maruza','Amaliy','Amaliy','Maruza'],
                    "Dars mahorati":['Yaxshi','Yaxshi','Yaxshi','Yaxshi','Yaxshi','Yaxshi','Yaxshi','Yaxshi','Yaxshi','Yaxshi']
                    })
print(oqtuvchilar)

oqtuvchilar.to_excel('oqtuvchilar.xlsx')